---
version: '2'
services:
  openldap:
    image: osixia/openldap:1.3.0
    hostname: openldap
    container_name: openldap
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: "example"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: "dc=example,dc=com"
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - ./src/test/resources/ldap/bootstrap-openldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif:ro
    command: "--copy-service --loglevel debug"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.4.1
    hostname: broker
    container_name: broker
    depends_on:
      - openldap
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
      - "9099:9099" # Added this port
    volumes:
      - ./target/simplest-possible-kafka-sasl-plaintext-ldap-authenticator-1.0-SNAPSHOT.jar:/usr/share/java/kafka/simplest-possible-kafka-sasl-plaintext-ldap-authenticator-1.0-SNAPSHOT.jar:ro
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASLPLAINTEXT:SASL_PLAINTEXT # Added SASLPLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092,SASLPLAINTEXT://broker:9099 # Added SASLPLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101

      # Settings for enabling the LdapAuthenticateCallbackHandler
      KAFKA_LISTENER_NAME_SASLPLAINTEXT_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS: no.shhsoft.kafka.auth.LdapAuthenticateCallbackHandler
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_SASLPLAINTEXT_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required ;

      # Settings for the LdapAuthenticateCallbackHandler
      KAFKA_AUTHN_LDAP_HOST: openldap
      KAFKA_AUTHN_LDAP_PORT: 389
      KAFKA_AUTHN_LDAP_BASE_DN: dc=example,dc=com
      KAFKA_AUTHN_LDAP_USERNAME_TO_DN_FORMAT: "cn=%s,ou=People,dc=example,dc=com"
